# Generated by Django 5.2.5 on 2025-09-07 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fitness equipment', 'Fitness Equipment'), ('socks', 'Socks'), ('ball', 'Ball'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('clothes', 'Clothes')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
