# Generated by Django 5.2.5 on 2025-09-21 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sportswear', 'Sportswear'), ('sports shoes & sandals', 'Sports Shoes & Sandals'), ('sports sccessories', 'Sports Accessories'), ('sports equipment', 'Sports Equipment'), ('health & fitness support', 'Health & Fitness Support'), ('protective gear', 'Protective Gear')], default='update', max_length=30),
        ),
    ]
